Add documentation for the <void/> marker
WoltLab/woltlab.github.io pull request #65
Opened 2020-08-19 09:37 UTC by TimWolla

Resolves #62

2020-08-19 16:45 UTC, Gravatronics requested changes

2020-08-19 16:45 UTC, Gravatronics commented on pages/package/package_package-xml.md
> +Instead of using a dummy `<instruction>` that idempotently updates some PIP the `<void/>` marker can be used for this use-case.
```suggestion
Instead of using a dummy `<instruction>` that idempotently updates some PIP, the `<void/>` tag can be used for this use-case.
```

2020-08-19 16:45 UTC, Gravatronics commented on pages/package/package_package-xml.md
> +However WoltLab Suite Core requires that the list of `<instructions>` is non-empty.
```suggestion
However, WoltLab Suite Core requires that the list of `<instructions>` is non-empty.
```

2020-08-19 16:45 UTC, Gravatronics commented on pages/package/package_package-xml.md
> +Using the `<void/>` marker is only valid for `<instructions type="update">` and must not be accompanied by other `<instruction>` tags.
```suggestion
Using the `<void/>` tag is only valid for `<instructions type="update">` and must not be accompanied by other `<instruction>` tags.
```

2020-08-25 13:21 UTC, dtdesign requested changes
Otherwise LGTM

2020-08-25 13:21 UTC, dtdesign commented on pages/package/package_package-xml.md
> +Sometimes a package update should only adjust the metadata of the package (e.g. because a new optional package was added).
```suggestion
Sometimes a package update should only adjust the metadata of the package, for example, an optional package was added.
```

2020-08-25 13:23 UTC, merged