Add AbstractEventListener documentation
WoltLab/woltlab.github.io pull request #70
Opened 2020-08-25 08:08 UTC by TimWolla

Resolves #63

2020-08-25 08:09 UTC, TimWolla commented on pages/tutorial/tutorial-series/tutorial_tutorial-series_part-2-event-listeners-and-template-listeners.md
> +  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calsl methods called `on` followed by the event name with the first character uppercased, passing the even
```suggestion
  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calls methods called `on` followed by the event name with the first character uppercased, passing the event object and the `$parameters` array.
```

2020-08-25 13:20 UTC, dtdesign approved these changes

2020-08-26 15:20 UTC, Gravatronics requested changes

2020-08-26 15:20 UTC, Gravatronics commented on pages/tutorial/tutorial-series/tutorial_tutorial-series_part-2-event-listeners-and-template-listeners.md
> +  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calls methods called `on` followed by the event name with the first character uppercased, passing the even
```suggestion
  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calls methods called `on` followed by the event name with the first character uppercased (an event named `foo` is processed by the method `onFoo`), passing the event object and the `$parameters` array.
```

2020-08-26 17:52 UTC, dtdesign commented on pages/tutorial/tutorial-series/tutorial_tutorial-series_part-2-event-listeners-and-template-listeners.md
> +  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calls methods called `on` followed by the event name with the first character uppercased (an event named `
```suggestion
  The `execute()` method of `AbstractEventListener` contains a dispatcher that automatically calls methods called `on` followed by the event name with the first character uppercased, passing the event object and the `$parameters` array. This simple pattern results in the event `foo` being forwarded to the method `onFoo($eventObj, $parameters)`.
```

Rationale: Inserting parts using paranthesis interrupt the flow. Having a dedicated sentence/example at the end acts as a short summary.

2020-08-28 16:13 UTC, Gravatronics approved these changes

2020-08-31 07:45 UTC, merged